language: generic
sudo: required
services: 
        - docker

before_install:
        - docker build -t prad05/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true prad05/docker-react npm run test

 
